-- CreateTable
CREATE TABLE "JarTopUp" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "jarId" INTEGER NOT NULL,
    "amountPln" DECIMAL(65,30) NOT NULL,
    "note" TEXT,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "JarTopUp_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "JarTopUp" ADD CONSTRAINT "JarTopUp_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "JarTopUp" ADD CONSTRAINT "JarTopUp_jarId_fkey" FOREIGN KEY ("jarId") REFERENCES "Jar"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
