ALTER TABLE "Jar" DROP COLUMN IF EXISTS "openingBalance";
ALTER TABLE "Jar" ADD COLUMN "openingBalanceLiz" DECIMAL(65,30) NOT NULL DEFAULT 0;
ALTER TABLE "Jar" ADD COLUMN "openingBalanceEdgar" DECIMAL(65,30) NOT NULL DEFAULT 0;
